#
# This is popup help messages for the Admin Panel -> Settings -> Alerts & Notices
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
new_ticket_alert:
    title: New Ticket Alert
    content: >
        Choose what Agents will be alerted when New Tickets are created by Clients.
        
status:
    title: Status
    content: >
        You may choose to disable whether any notice of New Tickets are sent out at
        all.
        
admin_email:
    title: Admin Email
    content: >
        
department_manager:
    title: Department Manager
    content: >
        
department_members:
    title: Department Members
    content: >
        
new_message_alert:
    title: New Message Alert
    content: >
        Alert sent out when a New Message from the Client is appended to an
        existing ticket.
        
status:
    title: Status
    content: >
        You may disable this Alert.
        
last_respondent:
    title: Last Respondent
    content: >
        Choose whether you would like the last Agent to have communicated with the
        Client to be Alerted of the Client’s reply.
        
assigned_staff:
    title: Assigned Staff
    content: >
        Choose whether you would like the Assigned Agent to receive an Alert of a
        Client’s reply.
        
department_manager:
    title: Department Manager
    content: >
        If enabled, the Department Manager’s Inbox could be flooded unnecessarily
        with Email Alerts. 
        
new_internal_note_alert:
    title: New Internal Note Alert
    content: >
        An Internal Note is extraneous information gathered in the Ticket panel for
        an Agent’s eyes only. Choose to whom you would like an Alert sent when an
        Agent takes down Internal Notes.
        
status:
    title: Status
    content: >
        
last_respondent:
    title: Last Respondent
    content: >
        If enabled, the last Agent to have communicated with the Client will
        receive an Alert that an Agent has recorded a new Internal Note on a Ticket
        with which they have been involved.
        
assigned_staff:
    title: Assigned Staff
    content: >
        If enabled, the last Agent assigned to the Ticket will receive an Alert
        that an Agent has recorded a new Internal Note.
        
department_manager:
    title: Department Manager
    content: >
        If enabled, the Department Manager’s Inbox could be flooded unnecessarily
        with Email Alerts. 
        
ticket_assignment_alert:
    title: Ticket Assignment Alert
    content: >
        
status:
    title: Status
    content: >
        
assigned_staff:
    title: Assigned Staff
    content: >
        If enabled, the Agent being assigned to a Ticket will receive an Alert
        notifying them of such.
        
team_lead:
    title: Team Lead
    content: >
        If enabled, if a Ticket is assigned to a Team, the Team Lead will be
        alerted of the new Assigned Ticket. (To manage your Teams, see Admin Panel
        -> Agent (Staff) Members -> Teams).
        
team_members:
    title: Team Members
    content: >
        If enabled, if a Ticket is assigned to a Team, the entire Team will be
        alerted of the new Assigned Ticket. This may cause an unnecessary amount of
        Email traffic and should be used with caution. (To manage your Teams, see
        Admin Panel -> Agent (Staff) Members -> Teams).
        
ticket_transfer_alert:
    title: Ticket Transfer Alert
    content: >
        
status:
    title: Status
    content: >
        
assigned_staff_team:
    title: Assigned Staff/Team
    content: >
        If enabled, the new Agent/Team of the targeted Department will be alerted
        of such.
        
department_manager:
    title: Department Manager
    content: >
        If enabled, when a Ticket is transferred to a new Department, the Manager
        of the targeted Department will be alerted of such.
        
department_members:
    title: Department Members
    content: >
        If enabled, the every member of the Targeted Department will receive an
        Alert of the Ticket Transfer. This may cause an unnecessary amount of Email
        traffic and should be used with caution.
        
overdue_ticket_alert:
    title: Overdue Ticket Alert
    content: >
        
status:
    title: Status
    content: >
        
assigned_staff_team:
    title: Assigned Staff/Team
    content: >
        The Agent or Team that is assigned to the Ticket entering an Overdue status
        will be alerted of such.
        
department_manager:
    title: Department Manager
    content: >
        The Manager of the Department whose Ticket enters an Overdue status will be
        alerted.
        
department_members:
    title: Department Members
    content: >
        If enabled, the every member of the Department will receive an Alert of the
        Overdue status of the Ticket. This may cause an unnecessary amount of Email
        traffic and should be used with caution.
        
system_alerts:
    title: System Alerts
    content: >
        
system_errors:
    title: System Errors
    content: >
        This is enabled by default. Alerts of System Errors are sent to the System
        Administrator’s Email.
        
excessive_login_attempts:
    title: Excessive Login Attempts
    content: >
        If enabled, the System Administrator will be alerted when a Client or Agent
        undergoes excessive failed login attempts.