#
# This is popup help messages for the Admin Panel -> Settings -> Tickets
#
# Fields:
# title - Shown in bold at the top of the popover window
# content - The body of the help popover
# links - List of links shows below the content
#   title - Link title
#   href - href of link (links starting with / are translated to the
#       helpdesk installation path)
#
# The key names such as 'helpdesk_name' should not be translated as they
# must match the HTML #ids put into the page template.
#
---
global_ticket_settings_options:
    title: Global Ticket Settings &amp; Options
    content: >
        These settings are <span class='doc-desc-title'>global,</span> in that they
        apply until they are overridden by other possible system settings (e.g., a
        Department’s SLA Plan overrides the Global Default SLA Plan set below).
        
ticket_ids:
    title: Ticket IDs
    content: >
        Choose between Random (Recommended) or Sequential numbers for tickets.
        
default_sla:
    title: Default SLA
    content: >
        Default Service Level Agreement Plan dictates how long a Ticket remains
        Open before it is marked Overdue.
        
default_priority:
    title: Default Priority
    content: >
        Choose a default priority level for new tickets throughout the system. Know
        that this setting can be overridden by <span class='doc-desc-title'>Email
        Accounts</span>, and <span class='doc-desc-title'>Ticket Filter
       </span> settings will override all settings. 
        
maximum_open_tickets:
    title: Maximum Open Tickets
    content: >
        Enter the maximum number of Open Tickets a Client is permitted to have
        simultaneously. This will help protect against spam and enable email flood
        control.   Enter 0 if you prefer to disable this limitation.
        
agent_collision_avoidance:
    title: Agent Collision Avoidance
    content: >
        Enter the length of time after an Agent stops ticket-response activity that
        a lockout period takes affect. This lockout prevents other Agents from
        sending a ticket response to the Client. It does not however prevent others
        from composing a draft. If the locking Agent sends their response, then any
        other Agent’s draft will be deleted. Enter 0 to disable the lockout
        feature.
        
email_ticket_priority:
    title: Email Ticket Priority
    content: >
        Use email priority assigned by addressee’s mail service
        
show_related_tickets:
    title: Show Related Tickets
    content: >
        Show all related tickets on user login - otherwise access is restricted to
        one ticket view per login
        
human_verification:
    title: Human Verification
    content: >
        Enable CAPTCHA on the Client Portal to verify an incoming ticket is the
        result of human activity.
        
auto_claim_tickets:
    title: Auto-Claim Tickets
    content: >
        Enable this to auto-assign unassigned tickets to the initial responding
        Agent.
        
assigned_tickets:
    title: Assigned Tickets
    content: >
        Enable this feature to make visible (in the Open Queue) Ticket Assignments
        that do not belong to the current user.
        
answered_tickets:
    title: Answered Tickets
    content: >
        Show tickets that have been answered by staff  in open queue. If not check,
        answered tickets will show up in a separate column until user responds,
        thereby moving it to the opened queue. 
        
staff_identity_masking:
    title: Staff Identity Masking
    content: >
        If enabled, this will hide the Agent’s name from the Client during any
        communication.
        
enable_html_ticket_thread:
    title: Enable HTML Ticket Thread
    content: >
        If enabled, this will permit the use of rich text formatting between
        Clients and Agents and Auto-Response emails. 
        
ticket_response_files:
    title: Ticket Response Files
    content: >
        Enable this if you would like for attachments within an Agent’s ticket
        response to be included in the Client’s email.